### ISSUE TITLE
ReadMe周りの気になったところ

### ISSUE THREAD

**Issue by zer0-u** [MasatoshiTada/spring5-boot2-handson#1]
# 全体のReadMe

## 開発環境
- JDK8な理由は何ですか？

## 開始前に
- IntelliJ IDEAの実行フォルダ設定
  - Configurationの新規追加が必要なので、この指示だけでは設定が変更できません
  - ReadMeを充実させるか、いっそハンズオン冒頭で設定を一緒に済ませるくらいの対応が必要そうです
- pom.xmlの確認
  - 01-spring5のpom.xmlの何がどうなっていればいいかがわからないので、確認しろと言われても困ります

**Comment by MasatoshiTada** [comment]
修正したのでクローズしまーす
