### ISSUE TITLE
importについて

### ISSUE THREAD

**Issue by kazuki43zoo** [MasatoshiTada/spring5-boot2-handson#13]
答えじゃない方に import が残っているのは意図的？それとも消し忘れ？

**Comment by MasatoshiTada** [comment]
はい、意図したものです。
Java言語自体に慣れていない方がIDEの補完を使わずに全て手でタイプしても、動くようにするためです。
（そこでつまるのは本ハンズオンの目的ではないため）

**Comment by kazuki43zoo** [comment]
> はい、意図したものです。

そんな気はしてたのですが、なんとなく気になったので。
