### ISSUE TITLE
TODO 2-04 「readOnly = trueについて」

### ISSUE THREAD

**Issue by kazuki43zoo** [MasatoshiTada/spring5-boot2-handson#14]
> readOnly = trueとすると、このメソッド内ではSELECT文しか発行できなくなります。

とありますが、以前このオプションを指定した場合の実際の動作を検証したことがあります。
その時の調査結果では、使用するDB(JDBCドライバ？)とPlatformTransactionManagerの組み合わせによって動作が違いました。調査したのが 2014年と結構昔なので、最新事情は変わっているかもしれませんが。

* https://github.com/terasolunaorg/terasoluna-tourreservation/issues/163

この時の調査ではH2は対象にしていませんが、「SELECT文しか発行できなくなります。」という表現は適切じゃない気がします。

**Comment by kazuki43zoo** [comment]
続報ですが、readOnly=trueでsaveメソッド実行したらテスト成功しちゃいました（＝insertできちゃいました）。

**Comment by MasatoshiTada** [comment]
いま改めて調べました。 `readOnly = true` にすると他のトランザクションからデータを更新されても影響を受けない、ということなんですね。
http://dba.fyicenter.com/faq/oracle/Set-READ-ONLY-Transaction.html
https://docs.oracle.com/cd/E60665_01/db112/SQLRF/statements_10005.htm
当トランザクションから更新処理が発行できなくなるという意味では無さそうですね。

うーん、文面どう変えようかな・・・

**Comment by MasatoshiTada** [comment]
Javadocによると、トランザクションマネージャーによっては `readOnly=true` を解釈できないものがあるみたいですね・・・。
https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/transaction/annotation/Transactional.html#readOnly--

上記の旨を注意書きとして書くのが良さそうです。

**Comment by MasatoshiTada** [comment]
追記しましたので、本件クローズします。
https://github.com/MasatoshiTada/spring5-boot2-handson/commit/19c89a3c9c57f374afa012e76b20d0bb97edefac
