### ISSUE TITLE
ODO 3-05 日付フォーマットについて

### ISSUE THREAD

**Issue by kazuki43zoo** [MasatoshiTada/spring5-boot2-handson#15]
ハンズオンの内容には直接関係ないですが、Date and Time APIの場合、日付フォーマットの年の部分を `yyyy` にするのか `uuuu` にするのか問題があったかと。

ちなみに・・・`@DateTimeFormat` で指定したフォーマットは、Springがこっそり！？ 「`yy` -> `uu`」 に変換してくれているのでハンズオンの内容で実際に問題が起こることはないんですけどね。（念のためコメントしておきます）

https://github.com/spring-projects/spring-framework/blob/95a56cd28dd2feb78d1f5d670a8e5f9a118a41e4/spring-context/src/main/java/org/springframework/format/datetime/standard/DateTimeFormatterFactory.java#L186

**Comment by MasatoshiTada** [comment]
ありがとうございます！コレ、知りませんでした😅
https://terasolunaorg.github.io/guideline/5.4.1.RELEASE/ja/ArchitectureInDetail/GeneralFuncDetail/DateAndTime.html#id10
問題が起こらないとは言え、上記のガイドライン通り `uuuu` に修正したほうがいいんでしょうか？

**Comment by MasatoshiTada** [comment]
`uuuu` に変更し、TODOにはTerasoluna開発ガイドラインへのリンクを追記しました。
https://github.com/MasatoshiTada/spring5-boot2-handson/commit/41c969178a0a2da2c88641fe2d8e159757c38bf5

本件クローズします。
