### ISSUE TITLE
01-spring5 のハンズオンをしながら思ったあれこれ

### ISSUE THREAD

**Issue by zer0-u** [MasatoshiTada/spring5-boot2-handson#2]
- IDEA上でtodo-01.mdを見ていない(ブラウザで見ながらIDEAで編集する)ので、ソースコードへのリンクがあってもあんまり役に立たないと感じる
  - どちらかというとパッケージ名まで明示されていたほうがわかりやすい

- 1-07
  - コード上のコメントでは`CrudRepository<Customer,Integer>`なのに、todo-01.mdでは型変数の部分が消えてるのが気になる

- 1-10
  - `namedParameterJdbcTemplate`の引数`dataSource`がコンパイルエラーになっている
  - IntelliJ IDEAの仕様上どうしようもないことは把握しているが、初めて見る人は驚くかもしれない
  - コメントなどでの補足が必要？

**Comment by zer0-u** [comment]
- 1-14
  - 1-10で指摘したことと同じ
  - `customerRepository`フィールドと`dataSource`がコンパイルエラー
  - どこかで補足したほうがよいと思う

**Comment by zer0-u** [comment]
- 2-07 🔥 
  - 戻り値をreturnしないのでは？
  - returnするならCustomerServiceのsaveメソッドの戻り値を修正すべき

**Comment by zer0-u** [comment]
それぞれのtodoがどういうことをやってるのかが見えづらい(ただの作業ゲーに思える)から、todo-01,02,03の単位で「こういうことをやります！」という道筋が示されていると嬉しいです

**Comment by zer0-u** [comment]
- 3-03 🔥 
  - ソースコードのコメントでは「長さ1から128まで」とありますが、todo-03.mdには「`@Length(min = 1, max = 32)`」とあります

**Comment by zer0-u** [comment]
- 3-10
  - `addAttribute`で「画面に渡せる」というのは知っている前提ですか？

**Comment by zer0-u** [comment]
- 3-18
  - `"redirect:/"`で`/`にリダイレクトできるというのは知っている前提ですか？

**Comment by zer0-u** [comment]
- 3-24,25
  - `setPrefix`や`setSuffix`メソッドを呼び出すところから書くのかと思った
  - 「引数の`null`を`hogehoge`に変更する」と伝えたほうが親切かもしれない

**Comment by zer0-u** [comment]
- 3-32,33
  - メソッドの書き方がまちまち
  - 3-12では「`insertMain`メソッド」
  - 32や33では「getServletMappings()」

**Comment by zer0-u** [comment]
- 3-31,32,33
  - それぞれのメソッドに`@Override`は不要ですか？

**Comment by zer0-u** [comment]
- 3-34 🔥 🔥 
  - `getServletConfigClassesTest`の期待値がそもそも違う気がする…
  - 指示通り実装すると戻り値(配列)の要素数は4
  - 期待値は5
  - `SecurityConfig.class`が抜けている…？

**Comment by zer0-u** [comment]
- 3-40 💨 
  - 「新規追加時に入力検証が実行されること」がどういう状況ならOKかわからない
  - この時点で未入力のまま登録ボタンを押すとTomcatのエラー画面(HTTP Status 405)が出る　

- 間違えてました 😇

**Comment by zer0-u** [comment]
- 4-02
  - 「Java Configであること、かつSpring Securityを有効化するために」
  - 「Java Configであることを示し、かつSpring Securityを有効化するために」(要素の粒度を揃える)

**Comment by zer0-u** [comment]
- 4-03
  - ここに来て突然説明が不親切になった…
  - ここまでは`@ComponentScan(basePackages = "...")`と例が出ていた

**Comment by zer0-u** [comment]
- 4-04
  - 各種メソッドの`@Override`は不要ですか？

**Comment by zer0-u** [comment]
- 4-12 🔥 
  - `AccountDetails`クラスは`UserDetails`インタフェースを実装しているように見えない
  - ただのクラスに見える

**Comment by zer0-u** [comment]
- 4-19(4-12関連)
  - `UserDetails`を実装してないと先に進めないので、こちらで勝手に実装しておきました

**Comment by zer0-u** [comment]
- 4-25 🔥 🔥 
  - この前に`MvcConfig`クラスの`getServletConfigClasses`メソッドの戻り値に`SecurityConfig.class`を追加しないと動かない(500になる)

**Comment by zer0-u** [comment]
- 4-25
  - 権限がなくて遷移できない場合のエラー画面はデフォルトのもので大丈夫ですか？

**Comment by zer0-u** [comment]
とりあえずこんな感じです

13:30に始めてツッコミをいれる＋休憩1回で14:50なのでわりと時間がきつい… 😇

**Comment by MasatoshiTada** [comment]
修正したのでクローズしまーす
