### ISSUE TITLE
03-boot2 のハンズオンをしながら思ったこと

### ISSUE THREAD

**Issue by zer0-u** [MasatoshiTada/spring5-boot2-handson#3]
🔥 がついているものは緊急度が高そうなものです(数が多いほどやばい)

**Comment by zer0-u** [comment]
- 5-02
  - ここで`DataSourceConfig`クラスを削除すると、`MvcInitializer`クラスがコンパイルエラーになる
    - `getServletConfigClasses`メソッドの戻り値に`DataSourceConfig.class`があるため
  - 後に(5-08)`MvcInitializer`クラスも削除するから問題ないとはいえちょっと気持ち悪い

**Comment by zer0-u** [comment]
- 5-09,10
  - 09で「次のTODOで行う」と書くくらいなら、そもそも順序を逆にすればよいのでは？

**Comment by zer0-u** [comment]
- 5-11
  - Boot 1時代はどういうふうに設定を書いてたんでしたっけ…？

**Comment by zer0-u** [comment]
- 5-12,13
  - 5-09,10と同様(順番を逆にすればよいのでは？)

**Comment by zer0-u** [comment]
ところでapplication.propertiesファイルのTodoコメントだけ英語っぽく書いてあるのが気になります

**Comment by zer0-u** [comment]
- 5-14
  - マークダウンのリンクの構文がうまく解析されてないっぽい
  - `[http://localhost:8080/]`と出てる

**Comment by zer0-u** [comment]
- 5-15 🔥 
  - 「pom.xmlに」Starterを追加？

**Comment by zer0-u** [comment]
- 5-17,18 🔥 
  - ソースコード中にコメントがないので「この行」がどこかちょっと迷った

**Comment by zer0-u** [comment]
- 5-18
  - `Actuatorの/actuator/**というURLには`
  - `Actuator`とは…？

**Comment by zer0-u** [comment]
- 5-19 💨 
  - `jq`ってなんですか…？

→ インストールしたら動いた(セットアップ漏れ)

**Comment by zer0-u** [comment]
とりあえず無我夢中で駆け抜けて15:20です

**Comment by MasatoshiTada** [comment]
修正したのでクローズしまーす
